sudo: required
services: 
    - docker

before_install:
    - docker build -t l01c/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true l01c/docker-react npm run test

deploy: 
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-839050490195"
    bucket_path: "docker-react"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
        branch: master

